export const TYPE_INTRODUCR = {
    BOOKING_GUIDE:"BOOKING_GUIDE",
    ABOUT_US:"ABOUT_US",
    CONTACT_US:"CONTACT_US",
    AFFILATE_POLICY:"AFFILATE_POLICY",
    TERMS_AND_CONDITIONS:"TERMS_AND_CONDITIONS",
    PRIVACY_POLICY:"PRIVACY_POLICY",
}